#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Lehrveranstaltungen von Jan Kus

# Short bio or description (displayed in the header)
description: Alle Informationen rund die Module "Projektarbeit - Vision und Konzept im Kontext des Studienschwerpunkts" und "Trustable Applications"

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/th-koeln/mi-2017/master/images/box.png

# Where are we?
timezone: Europe/Berlin

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: jan.kus@th-koeln.de
  facebook: https://fb.com/jbvkoos
  flickr: https://flickr.com/photos/jbvkoos
  github: https://github.com/koos
  instagram: https://instagram.com/jbvkoos
  linkedin: https://linkedin.com/in/jbvkoos
  pinterest: https://pinterest.com/jbvkoos  
  rss: # just type anything here for a working RSS icon
  twitter: koos
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: mikoeln
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 251080357

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://koos.github.io/mi-master-vuk/
deployurl: https://koos.github.io/mi-master-vuk/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/mi-master-vuk"

teaserimage: "joshua-earle-Dwheufds6kQ-unsplash.jpg"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# be sure that you use kramdown as markdown processor
markdown: kramdown

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  extensions: [footnotes]
  footnote_location: 'my_footnotes'
  parse_block_html: true
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Zur Abtrannung der marginalie
excerpt_separator: "<!--marginalie-->"

# Use the following plug-ins
plugins_dir:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-livereload

# Exclude these files from your production _site
exclude: ['Gemfile', 'Gemfile.lock', 'LICENSE', 'README.md', 'CNAME','_repos']

collections:
  lehrveranstaltungen:
    output: true
  workshops:
    output: true
  resources:
    output: true
  webtechnologien:
    output: false
  projektthemen:
    output: true

defaults:
  -
    scope:
      path: ""
      type: lehrveranstaltungen
    values:
      layout: lehrveranstaltung
  -
    scope:
      path: ""
      type: faq
    values:
      layout: faq
